In [1]:
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 27 09:52:46 2019

@author: leila
"""

#1. Import the NUMPY package under the name np.

import numpy as np

#2. Print the NUMPY version and the configuration.

print(np.__version__)
print(np.show_config())


1.17.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


In [2]:

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

#Solution 1 : ask np to do 2 lists of 3 lists with 5 values
a = np.random.random((2,3,5))
print(a)

[[[0.91328374 0.7775166  0.91235125 0.61543902 0.47833068]
  [0.79531529 0.33494419 0.4388135  0.78456021 0.53832667]
  [0.35824368 0.95815725 0.28379073 0.41615495 0.88484227]]

 [[0.89392358 0.65734649 0.5411469  0.13899177 0.2166955 ]
  [0.58279661 0.39299433 0.78839074 0.17571251 0.44369191]
  [0.54137263 0.14899504 0.93723839 0.39096297 0.51465619]]]


In [13]:

# #2nd 
# b = np.array([[1,2,3,4,5], [7,8,4,5,6] ,[9,6,7,8,9]],
#              [[1,2,3,4,5] [7,8,4,5,6], [9,6,7,8,9]])
# b



In [3]:

#4. Print a.

#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5,2,3))

In [4]:
#6. Print b.
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [5]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(np.size(a),np.size(b))
# the both size is 30

30 30


In [6]:
#8. Are you able to add a and b? Why or why not?
np.concatenate((a,b))
# NO :  all the input array dimensions for the concatenation axis must match exactly, 
# but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [7]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c=b.transpose((1,2,0))
c


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [8]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d= np.add(a,c)
d

array([[[1.91328374, 1.7775166 , 1.91235125, 1.61543902, 1.47833068],
        [1.79531529, 1.33494419, 1.4388135 , 1.78456021, 1.53832667],
        [1.35824368, 1.95815725, 1.28379073, 1.41615495, 1.88484227]],

       [[1.89392358, 1.65734649, 1.5411469 , 1.13899177, 1.2166955 ],
        [1.58279661, 1.39299433, 1.78839074, 1.17571251, 1.44369191],
        [1.54137263, 1.14899504, 1.93723839, 1.39096297, 1.51465619]]])

In [9]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a,d)
#teh dif is 1. 

[[[0.91328374 0.7775166  0.91235125 0.61543902 0.47833068]
  [0.79531529 0.33494419 0.4388135  0.78456021 0.53832667]
  [0.35824368 0.95815725 0.28379073 0.41615495 0.88484227]]

 [[0.89392358 0.65734649 0.5411469  0.13899177 0.2166955 ]
  [0.58279661 0.39299433 0.78839074 0.17571251 0.44369191]
  [0.54137263 0.14899504 0.93723839 0.39096297 0.51465619]]] [[[1.91328374 1.7775166  1.91235125 1.61543902 1.47833068]
  [1.79531529 1.33494419 1.4388135  1.78456021 1.53832667]
  [1.35824368 1.95815725 1.28379073 1.41615495 1.88484227]]

 [[1.89392358 1.65734649 1.5411469  1.13899177 1.2166955 ]
  [1.58279661 1.39299433 1.78839074 1.17571251 1.44369191]
  [1.54137263 1.14899504 1.93723839 1.39096297 1.51465619]]]


In [10]:
#12. Multiply a and c. Assign the result to e.
e=a*c

In [ ]:
#13. Does e equal to a? Why or why not?
#Yes it's * by 1

In [11]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_min=np.nanmin(d)
d_max=np.nanmax(d)
d_mean=np.mean(d)
print(d_min,d_max,d_mean)

1.1389917696801657 1.958157249624872 1.5618328534837052


In [12]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.zeros(shape=(2,3,5))
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [47]:
# """
# #16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, 
# assign 25 to the corresponding value in f.
# If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
# If a value equals to d_mean, assign 50 to the corresponding value in f.
# Assign 0 to the corresponding value(s) in f for d_min in d.
# Assign 100 to the corresponding value(s) in f for d_max in d.
# In the end, f should have only the following values: 0, 25, 50, 75, and 100.
# Note: you don't have to use Numpy in this question.
# """
# def new_f(x):
#     for x in d:
#         if d_mean>x>d_min:
#             x==25
#         elif d_max>x>d_mean:
#             x==75
#         elif x==d_mean:
#             x==50
#         elif x==d_min:
#             x==0
#         else:
#             x==d_max
#             x==100
#         return 
    
# new_f(f)
# fx= [in d (lambda x: x==25 if d_mean>x>d_min else 0)]
# f[d.where(image_array < 90)] = 0
# f[d.where(lambda x: 100 if x==d_max(x==25 if d_mean>x>d_min else x==75 if d_max>x>d_mean else x==50 if x==d_mean else x==0 if x==d_min)]

          
          
          # f.where(lambda x: 100 if x in d==d_max (x==25 if d_mean>x>d_min in d else x==75 if d_max>x>d_mean in d else x==50 if x==d_mean in d else x==0 if x==d_min in d)
# test= lambda x : 100 if x==d_max in d else (x==1)
# test(f)
# converter = lambda x : x*2 if x < 10 else (x*3 if x < 20 else x)

# lambda <args> : <return Value> if <condition > ( <return value > if <condition> else <return value>)
# for i in i in d:
# #     if d_mean>i>d_min:
# #         f(i)==25
# #     elif d_max>i>d_mean:
# #         f(i)==75
# #     elif i==d_mean:
# #         f(i)==50
# #     elif i==d_min:
# #         f(i)==0
# #     else:
# #         i==d_max
# #         f(i)==100
# # print(f)
# # [i in i in d if d_mean>i>d_min==25 else d_max>i>d_mean==75 else i==d_mean==50 else i==d_min==0 else i==d_max==100]
# #         >>> ["Even" if i%2==0 else "Odd" for i in range(8)]

In [71]:

"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""





'\n#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])\nAgain, you don\'t need Numpy in this question.\n'

In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""